### ISSUE TITLE
Upcoming fixed-vector release

### ISSUE THREAD

**Issue by Shimuuar** [leventov/yarr#6]
I'm going to release new version `fixed-vector` after weekend. It have number of improvements which are in part taken from yarr. This will

 1. NFData instances. Orphans in yarr will clash with instances from fixed-vector

 2. Storable instances for all suitable data types added.  Yarr have very evil orphan `Storable (v e)` which overlaps with everything of `* → *` kind. It probably should be removed

 3. Some combinators (zipWith3, zipWithM_) are copied into f-v so they could be dropped from yarr.

**Comment by idontgetoutmuch** [comment]
Thanks for letting me know. I'll take a look tomorrow.

**Comment by Shimuuar** [comment]
I'm going to hold off release until yarr breakage is sorted out
27.03.2015 18:39 пользователь "idontgetoutmuch" <notifications@github.com>
написал:

**Comment by idontgetoutmuch** [comment]
Ok - it is now working. Let me know what the new version number and I will update the cabal file so that it picks up the new version.

**Comment by Shimuuar** [comment]
Sorry for delay 

Next version is going to be 0.8

I don't understand last part. You did remove catch-all orphan for Storable and had to add `Storable (v e)` constraint. I don't see any problem with it. It could be removed probably

**Comment by idontgetoutmuch** [comment]
New version released - thanks!
